---
- hosts: oss
  remote_user: root

  tasks:
  - name: create tong user
    ansible.builtin.user:
      name: tong
      system: true
  
  - name: cofigure jdk env
    ansible.builtin.copy:
      src: /home/tong/jdk-8u241-linux-x64.tar.gz
      desc: /home/tong/
      remote_src: true
      owner: tong
      group: tong
  
  - name: unarchive jdk
    ansibel.builtin.command:
      chdir: /home/tong
      cmd: /usr/bin/tar -xf jdk-8u241-linux-x64.tar.gz
  
  - name: configure /etc/profile
    ansibel.builtin.command: /usr/bin/cat >> /etc/profile <<EOF
export JAVA_HOME=/home/tong/jdk1.8.0_241
export CLASS_PATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar:$JAVA_HOME/jre/lib/rt.jar
export PATH=$JAVA_HOME/bin:$PATH:$HOME/bin
EOF

#  - name: cofigure jdk env using unarchiving
#    unarchive:
#      src: /home/tong/jdk-8u241-linux-x64.tar.gz
#      desc: /home/tong/
#      owner: tong
#      group: tong

### check whether have copyed jdk
#  - name: add envariment for jdk
#    command: echo 
      
  - name: create project directory
    ansible.builtin.file: 
      path: /home/tong/wx-tong/resource/resend
      recurse: true
      state: directory
      owner: tong
      group: tong
  
  - name: create log directory
    ansible.builtin.file: 
      path: /home/tong/log
      recurse: true
      state: directory
      owner: tong
      group: tong

  - name: create tomcat directory
    ansible.builtin.file: 
      path: /home/tong/tomcat
      recurse: true
      state: directory
      owner: tong
      group: tong

